### PR TITLE
fix(ssi): disable SSI publishers when storage is unwritable

### LINKED ISSUE #58: CSI Driver version 1.2.0 is broken on GKE Autopilot.
Error message from `csi-node-driver` container:
`{"time":"2026-02-13T08:53:57.989288796Z","level":"ERROR","msg":"Fatal error","error":"failed starting csi driver: failed to create storage base path: mkdir /var/lib/datadog-csi-driver: read-only file system"}`

CSI Driver is enabled through Datadog helm chart v3.170.1 with `datadog.csi.enabled: true`

CSI Driver v1.1.1 works fine.

### PR DESCRIPTION
**Pull request by iamluc**
### What does this PR do?

This PR makes SSI storage optional at runtime when `storageBasePath` cannot be created or written to. Instead of failing driver initialization, the driver now disables storage-dependent SSI publishers and continues to start normally.

It also adds targeted tests for writable and non-writable storage configurations, and updates the changelog accordingly.

### Motivation

Attempt to fix https://github.com/DataDog/datadog-csi-driver/issues/58

The previous behavior caused the driver to fail at startup when `storageBasePath` was present but not writable. In practice, this is more disruptive than necessary because only SSI features depend on that storage path.

This change makes the driver more robust by degrading gracefully: SSI storage is disabled when unusable, while the rest of the driver remains available.

### Additional Notes

A small internal constructor refactor was added to improve testability of the storage setup path and logging behavior.

The `LibraryManager` now also receives the injected filesystem in tests, which keeps constructor behavior consistent.

### Describe your test plan

- Run unit tests:
  - `go test ./pkg/driver/...`

- Verify the following covered cases:
  - `createStorageDir()` returns no error for an empty path
  - `createStorageDir()` returns an error when `MkdirAll` fails
  - `createStorageDir()` returns an error when the storage path is not writable
  - `newDatadogCSIDriver()` creates a `LibraryManager` when storage is writable
  - `newDatadogCSIDriver()` logs SSI storage disablement and skips SSI storage setup when storage is not writable
  - storage-dependent SSI publishers are not registered when `storageBasePath` is empty

### CODE REVIEW

File: pkg/driver/publishers/publishers.go [hunk 1]
```diff
@@ -46,11 +46,19 @@ func GetPublishers(
...
+	var publishers []Publisher
+
+	// These publishers require writable storage
+	if storageBasePath != "" {
+		publishers = append(publishers,
+			// SSI publishers (library and injector preload)
+			newLibraryPublisher(fs, mounter, libraryManager, !apmEnabled),
+			newInjectorPreloadPublisher(fs, mounter, storageBasePath, !apmEnabled),
+		)
+	}
```
Comment (adel121) [inline pkg/driver/publishers/publishers.go:62]: nit: maybe a warning log here can be helpful in case storageBasePath == ""

**Review by adel121 — DISMISSED** [review]
Approving with a minor nit.

**Review by adel121 — APPROVED** [review]
